COMPONENT=TestHomeCommC
CFLAGS += -I/home/chuka/projects/puppet-os/system/\
-L/home/chuka/projects/puppet-os/system/\
-I/home/chuka/projects/puppet-os/interfaces/\
-I/usr/local/lib/puppet/c/\
-I/usr/local/lib/puppet/c/\
-I/opt/tinyos-2.1.1/tos/lib/net/\
-I/opt/tinyos-2.1.1/tos/lib/net/ctp\
-I/opt/tinyos-2.1.1/tos/lib/net/4bitle

include $(MAKERULES)

