COMPONENT=TestConfiguratorC
CFLAGS=-I/home/chuka/projects/puppet-os/system/\
-L/home/chuka/projects/puppet-os/system/\
-I/home/chuka/projects/puppet-os/interfaces/\
-I/home/chuka/projects/puppet-os/types/
include $(MAKERULES)

